### ISSUE TITLE
Turn off Scality RING server logging

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#113]
I was informed that during a Scality call that I missed it was suggested to turn-off Scality RING server logging as it could severely impact performance. Ron was going to do this and Chris Hoffman was to retest performance (I'll create another issue for Chris H.).

**Comment by dmgrimal** [comment]
Hey Brett,

Specifically, the concern is that the logging is being written to an NFS share since the servers are diskless in terms of OS.  During normal operation of the ring, the logs would be written to a local disk.  

Logging is not actually necessary and can be enabled on the fly as needed.  Also, as opposed to logging directly to the disk, we can redirect directly over syslog if you do want to have the logs all the time.

**Comment by brettkettering** [comment]
From Ron Croonenberg:

That was already taken care of last week.  First thing this morning ODSU was rebooted (it was it's DST) so the setting took effect.

**Comment by brettkettering** [comment]
More information from Dan Grimaldi:

Sorry for the alarm here.  I do not believe we are talking about a security risk.  The logs we are talking about are solely based on our processes.  They include key information at most and whether or not a key made it to the system.  There are other logs related to tasks and disk operations.  These logs are not critical to operation of the ring though they do have all operations which are happening.  

The problem we saw with the logs is that, as opposed to going straight to the syslog process for offloading, they were being written first to /var/log/scality-node-[1-6]/ and then rsyslog would come in and scrap the log files to send to a central syslog server.  These /var/log/scality-node* directories were originally on the NFS server but the directories were removed.  This meant the logs were writing directly to the ramdisk and then being scrapped by rsyslog.  This is why I told them to disable them since they would be eating up memory on the servers.
