### ISSUE TITLE
Files created by user with fuse are in root group

### ISSUE THREAD

**Issue by cadejager** [mar-file-system/marfs#12]
If I create a file as a user in marfs the group is set to root. This is with fuse.

Example:
[dejager@conn001 bin]$ echo "It was nice to meet you" > /marfs/dejager/goodbye
[dejager@conn001 bin]$ ls -lh /marfs/dejager/goodbye
-rw-r--r-- 1 dejager root 24 Oct  8 11:14 /marfs/dejager/goodbye

**Comment by jti-lanl** [comment]
Good catch.  Fixed now.

**Comment by jti-lanl** [comment]
Hi Chris,

This is fixed now.  However, I noticed some other issues you are probably running into, doing file-operations as a regular user.

One thing is that you might not have access to the trash directory (configured as /gpfs/fs2/trash, for you, I think).  I did all of the
following, which I believe could've been giving you spurious permissions problems:

chown -R 26158:26158 /gpfs/fs1/trash/dejager.0/
chown -R 26158:26158 /gpfs/fs1/dejager/fsinfo
chown -R 26158:26158 /gpfs/fs1/dejager/mdfs

These are things we are expecting admins to do, when creating a new namespace

The first one is potentially a problem, when we get to phase 2, because they won't know how many shards the trash
might potentially have.  I propose we create a single model directory, and fuse can create the requisite directories, copying
ownership from the model-dir.

Thanks,
Jeff
