### ISSUE TITLE
GC Issue with Spaces

### ISSUE THREAD

**Issue by quick1234** [mar-file-system/marfs#159]
When running Garbage Collection there is an issue when there are spaces in the file name.

For example:
/gpfs/marfs/trash/admins.0/6/8/9/07 Example.pdf.trash(....)

It attempts to stat_xattrs using this path:
/gpfs/marfs/trash/admins.0/6/8/9/07

**Comment by jti-lanl** [comment]
Thanks.  Looks to me like that stat_xattrs() call shouldn't even be there, because we've already gotten the xattrs we want from the gpfs scan.  Some pending changes to support object-deletes via the DAL will also remove that stat_xattrs() call.  That should speed GC up considerably, and make this particular problem moot.

However, we should still investigate this particular problem, so that we can fix it for wherever else it may be potential.

**Comment by jti-lanl** [comment]
Fixed in the gc-dal branch.  There was a problem with the format used in str_2_post().
