### ISSUE TITLE
Should rebuilder skip objects that have all N+E blocks present?

### ISSUE THREAD

**Issue by wfvining** [mar-file-system/marfs#186]
The primary purpose of the rebuilder is to reconstruct blocks that were lost when an entire file system has failed. We want this to run in the background while new objects are being added in the usual way (pftool).

As a quick check for whether an object should be rebuilt we can verify that all N+E blocks are present and skip objects that have all blocks. This will leave open the possibility of silent data corruption, since the checksums will not be verified for skipped objects, but should save time by not reading newly written (and intact) objects. Would this be worth the effort? In reality the number of new objects added will likely be dwarfed by the number of objects that need to be rebuilt, meaning we won't actually save that much time.

**Comment by gransom** [comment]
As pointed out in the original description of this issue, the gains from implementing this functionality are likely to be minimal, as the number of objects requiring rebuilds will likely vastly outweigh the number of newly written objects since restoration of the missing capacity unit.  I would expect this ratio to be >>99% requiring rebuild if the system has been up for any considerable length of time.  If the system has been quiesced/halted as part of near-disaster recovery (as would almost certainly be recommended), it would mean that literally every object requires a rebuild, and this approach wouldn't save any time.
Considering this, I strongly suspect that implementing even a stat("/path/to/bad/cap-unit"), for every object, to check if rebuild is necessary would actually slow the rebuild process down more than simply performing some unnecessary rebuilds (which would really just be rereads of the problem objects).

**Comment by thewacokid** [comment]
Considering the cost to implement versus the minimal gains...closing this.
