### ISSUE TITLE
Implement full marfs_statfs()

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#36]
Refer to the initial explanation in #34 Implement "fake" marfs_statfs().

In the full version, we will have Alfred’s tool create an fsinfo in the root namespace where the sum of everything lives.

**Comment by jti-lanl** [comment]
See item #34 

The current state of affairs has commented-out code to take care of finding the currently-used capacity.  In order to compute the real current usage, we can either read through all the fsinfos in all namespaces and add them up to get the total usage, or we can refer to the file where the root-namespace fsinfo is configured, which could be filled in by Alfred's tool.  Either way, we get the total storage used by all namespaces, but the latter approach requires only 1 stat.

However, if we want to say how much storage is *available*, what do we do?  We don't want every call to statvfs()/df to go probe the storage system to see how much space is available.  (Or do we?)  And the storage available in the MDFS is not the true limit of our capacity (though it does represent the limit of inodes ... until we get to sharding).

Maybe we want the periodic scan to also do queries of the object-store, etc, and initialize other files, so statvfs can report the correct limits on capacity?  Or maybe statvfs just takes as long as it takes, to get correct info.

**Comment by brettkettering** [comment]
We can get by without this for Secure Campaign, but let's implement it if we have time.

**Comment by Brofessional** [comment]
Stale issue cleanup
