### ISSUE TITLE
File versioning

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#54]
Version the data behind files since unlink and truncate put old "space" of file in the trash.

**Comment by jti-lanl** [comment]
I don't understand what this means.  Is it about having multiple versions of the same file in the trash, all referring to different data?  I believe we've got that covered.

**Comment by brettkettering** [comment]
I'm not sure either. At first I was thinking of the MarFS version that put it in the trash, but I'm not sure what difference that would make.

**Comment by jti-lanl** [comment]
I think this could mean one of two things:

(a)  Different versions of marfs could have written the different versions of a file in the trash.  We need to be able to tell which version wrote each file, so that we can maintain our ability to read each file.   **We have that covered** in terms of the version-number in the object-ID xattr, which is attached to respective old versions of a file.  (Though we have not yet conditionalized our readers to distinguish different historical formats.  We will probably start doing that with v1.0.)

Alternatively, it could mean we want to be sure we can tell which version of a file in the trash was written when.  **We have that covered** in the pathname of the trash-file, which is the original file-name plus an extension that identifies the time it was created in the trash.

So, I think this can be closed.
