### ISSUE TITLE
Metadata update logging

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#56]
Trying to limit what must be scanned. Are there triggers that can be set when files are accessed that would tell us what needs to be considered or not?

**Comment by jti-lanl** [comment]
Is the goal is to reduce the number of files to consider, when updating quota information?  I believe the inode scan sees inodes and mtimes, so it only needs to consider files that are newer than the previous scan (assuming our ops update mtimes).  But maybe there are other scans where it's more costly to determine whether an inode should be considered?  For packing, I believe we can see those xattrs that fit in the inode, which for us should be all of them, so, again, maybe we could easily eliminate files that are already packed or too big.

For cases beyond these, libmarfs could maintain a bloom-filter.  On every relevant file update, hash the path (or better yet the inode) through k different hashes, and touch appropriate cells in the filter.  Then, during the scan, skip everything that hashes to a set that includes an untouched filter-cell.  Wipe the filter after each run.  We'd get some false positives, but perhaps we could identify them as such, during the more-expensive tests that are done with files that pass the filter.  Apparently, it can take some effort to design k hash-functions with uniform(-ish) distribution.  There are some variants that are supposed to scale.

A filter of, say, 16 MB would give us 128 Mbits, or 2^28 cells.  So, for 32-bit inodes, with a single (null) hash-function, we'd expect 16 collisions per cell, if we ran it for the time it took users to create all possible inodes.  But of course we'd be cleaning it out more often than that, when we ran the scans.  No fancy locking needed for updates; just iterate with CMPXCHG, when doing updates.  We would either have to prevent file updates during the scan, or lose track of some files updated during the scan.

If by scanning you mean a tree-walk, the above approach would still work, but we could instead do something like this: update the mtime of a directory every time a file is modified.  This would add some overhead to all file ops, but then we could skip any files in directories with an mtime older than the most-recent walk, though we'd still have to look at all directories.

Updating mtimes in all the parent dirs of any updated dir would make the tree-walking easier, because you'd know when you could stop descending the tree, but it would also add a greater (ridiculous?) cost to all file-ops.

**Comment by Brofessional** [comment]
Stale issue cleanup
