### ISSUE TITLE
Implement data compression

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#57]
This is probably best done by integrating a data store that compresses. Otherwise, we need to look at compression algorithms and decide on which ones might be useful to us. The hard part is how to read compressed files/chunks in FUSE.

**Comment by jti-lanl** [comment]
If the storage system does the compression, then recovery info gets compressed, too.  (But FUSE is easy.)  Otherwise, fuse could skip compressing the recovery-info.

If compression algorithms change over time, it could be tricky to do recovery without the MDFS to tell you which object was compressed how, but perhaps if we have some record of how the algorithms changed over time (e.g. Scality release install history), we can tend to pick the correct algorithm.

It may mean decompressing an entire object before you can pick out the recovery info at the end.

If we save a record associating MarFS object-IDs and the Scality object-IDs that they hash to, then a crawl of object-IDs could provide compression-algorithms used.

**Comment by Brofessional** [comment]
Stale issue cleanup
