### ISSUE TITLE
Sharded metadata

### ISSUE THREAD

**Issue by brettkettering** [mar-file-system/marfs#69]
This is for metadata scaling. It is not something we need all that soon, but it is something that will sell MarFS.  It is the highest odds of winning a best paper somewhere of all the things about MarFS.  For this reason, we could farm this out to a company as long as we get to co-author.  I know it would be nice for us to do this work, but it would make for a huge announcement.  MarFS system easily tames 1 trillion files.

**Comment by brettkettering** [comment]
Do this as part of the Program Development demonstration project.

**Comment by jti-lanl** [comment]
MarFS should use the MDAL (See #83) to implement this.  In fact, part of the motivation for having distinct MDAL specs for directory and file operations is to support sharding.

I think the idea is that we might want PVFS2 for MD directory ops, because that supports client-side caching.  Every time we do a MD file-create, there's going to be a chase through the MD directory tree, to validate access.  Having client-side caching will save a trip over the interconnect, plus contention for resources/locks on the server.  In addition, PVFS2 apparently has cheap directory-inserts, just updating a DB.  (See also issue #100, about making this as cheap as possible.)

Then, the actual file insert might go through the same or a different MDAL (Gary is thinking maybe IOFSL), hashing the filename to find the server, and doing the insert on a filesystem that has cheap file-inserts.

**Implementation:**  Maybe we should discuss implementation.  We have been planning to use the suid or sgid bits on directories in the MDFS, to indicated sharding.  This is nice because it allows easy detection from a stat().  However, it seems conceivable that this low-level technique should be subsumed by an MDAL operation (e.g. `mdal_is_sharded(my_dir)`, or something).  That way, we don't require every MD implementation to support suid/sgid bits.  In fact, maybe sharding should be hidden inside even-higher-level ops, e.g. where `mdal_open()` simply takes care of all the internal ops needed to deal with sharded directories?  Hmm. but then we'd have a lot of duplicated code, e.g. to hash the filename, for each different MDAL implementation.  So, maybe we need a set of tools that can be used by MDAL implementations?  Getting too complicated, for now.  Stick with `mdal_is_sharded(my_dir)`.

**Comment by jti-lanl** [comment]
Didn't mean to close.

**Comment by jti-lanl** [comment]
This was item "(2)" in issue #83.  Moving here, so we can close that.

TBD: support directory sharding

-- I think we agreed there is another MDAL for talking to the shard FS.
-- extend config so Namespace can/must specify MDAL type for shards
-- code tweaks to identify sharded directories, and make calls through shard MDAL.

The point of this is to allow flexibility in the choice of the tech on which the shards are implemented. For the MD Scaling Demo project, we might picture talking IOFSL (or Cray's DVS) to the FSes where the shards live. The commands in the MDAL might as well be the union of ones needed to talk to the dir-MD and ones needed to talk to the file-MD (i.e. on the shard-FS). Then we really have two MDAL instantiations coming from the config.

**Comment by brettkettering** [comment]
The model has changed. This work is done in the application itself, not MarFS. Closing.
